services:
    hotfix.geoname.import.timezone:
        class: Hotfix\Bundle\GeoNameBundle\Import\TimeZoneImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    hotfix.geoname.import.administrative:
        class: Hotfix\Bundle\GeoNameBundle\Import\AdministrativeImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    hotfix.geoname.import.geoname:
        class: Hotfix\Bundle\GeoNameBundle\Import\GeoNameImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    hotfix.geoname.import.country:
        class: Hotfix\Bundle\GeoNameBundle\Import\CountryImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    hotfix.geoname.import.hierarchy:
        class: Hotfix\Bundle\GeoNameBundle\Import\HierarchyImport
        arguments: ["@doctrine.orm.default_entity_manager"]
        public: true

    #auto register all commands
    hotfix.geoname.command.import:
        class: Hotfix\Bundle\GeoNameBundle\Command\ImportCommand
        tags:
              - { name: console.command }