services:
    _defaults:
        autowire: true

    Hotfix\Bundle\GeoNameBundle\Service\Import\:
        resource: '../../Service/Import/*'
        tags: [hotfix.geoname.import]

    Hotfix\Bundle\GeoNameBundle\Service\Importer:
        arguments:
            $imports: !tagged_iterator hotfix.geoname.import

    Hotfix\Bundle\GeoNameBundle\Service\Downloader:

    Hotfix\Bundle\GeoNameBundle\Command\ImportCommand:
        arguments:
            $cacheDir: '%kernel.cache_dir%'
        tags: [console.command]

    Hotfix\Bundle\GeoNameBundle\Repository\:
        resource: '../../Repository/*'
        tags: [doctrine.repository_service]